services:

  traefik:
    image: traefik:v3.0
    container_name: "mapproxy_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8090:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mapproxy:
    image: kartoza/mapproxy
    volumes:
      - ./mapproxy:/mapproxy
    ports:
      - 8000:8080
    labels:
      - "traefik.http.routers.map_mapproxy.rule=Host(`mapproxy.map.localhost`)"
    expose:
      - 8080
   # networks: 
   #   - internal_network

  terrain:
    image: node:alpine
    working_dir: /usr/src/app
    user: node
    volumes:
      - ./terrain:/usr/src/app
    command: sh -c 'npx http-server'  
    ports:
      - 8001:8080
    labels:
      - "traefik.http.routers.map_terrain.rule=Host(`terrain.map.localhost`)"
    expose:
      - 8080
      
  3dtiles:
    image: node:alpine
    working_dir: /usr/src/app
    user: node
    volumes:
      - ./3dtiles:/usr/src/app
    command: sh -c 'npx http-server'  
    ports:
      - 8002:8080
    labels:
      - "traefik.http.routers.map_3dtiles.rule=Host(`3dtiles.map.localhost`)"
    expose:
      - 8080
      
  app:
    image: node:alpine
    working_dir: /usr/src/app
    user: node
    volumes:
      - ./app:/usr/src/app
    command: sh -c 'npx http-server'    
    ports:
      - 8080:8080
    labels:
      - "traefik.http.routers.map_app.rule=Host(`map.localhost`)"
    expose:
      - 8080

networks:
  internal_network:
    internal: true
