services:

  traefik:
    image: traefik:v3.0
    container_name: "mapproxy_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8090:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mapproxy:
    image: kartoza/mapproxy
    volumes:
      - ./mapproxy.yaml:/mapproxy/mapproxy.yaml
      - ./seed.yaml:/mapproxy/seed.yaml
      - ./imagery:/mapproxy/cache_data/imagery_cache_EPSG3857
    ports:
      - 8000:8080
    labels:
      - "traefik.http.routers.map_mapproxy.rule=Host(`mapproxy.map.localhost`)"
    expose:
      - 8080
   # networks: 
   #   - internal_network

  app:
    image: node:24-alpine
    working_dir: /usr/src/app
    user: node
    volumes:
      - ./:/usr/src/app
    command: sh -c 'yarn && node server.js'
    ports:
      - 8080:8080
    labels:
      - "traefik.http.routers.map_app.rule=Host(`map.localhost`)"
    expose:
      - 8080

networks:
  internal_network:
    internal: true
